### ISSUE TITLE
remove more special characters from sql query

### ISSUE THREAD

**Issue by whohoho** [ether/ueberDB#107]
There is a bug in etherpad-lite that allows you to download all pads.

They pointed out that this might be a bug in ueberDB.

Here some special characters get removed.
https://github.com/Pita/ueberDB/blob/5c2ef4dc1476ef24bc475885817816c3e602ec8b/mysql_db.js#L133

_  (and possible more) is a special character as well.

See: 
https://dev.mysql.com/doc/refman/5.7/en/pattern-matching.html
https://github.com/ether/etherpad-lite/issues/3169

**Comment by nashe** [comment]
Since the use of pattern matching (MySQL, etc) / regular expressions (dirtydb) may be a wanted behavior, it would be great to implement an `escape` method for each supported database so clients (eg. `etherpad-lite`) can apply it on user-controlled data.

**Comment by JohnMcLear** [comment]
Responsible disclosure.....

**Comment by nashe** [comment]
This issue already exists on etherpad for months :-/ By the way, I tried to contact you about this subject (but not only) two days ago by email.

**Comment by JohnMcLear** [comment]
Did your email bounce?  Did you get a response?  I haven't seen anything... ;\  I have been handling other CVE and Security related topics successfully over the previous months with no major problems.

**Comment by JohnMcLear** [comment]
Just so understand the scope of this bug:

1. Allows user to request downloading all pad contents.  Most times it will fail due to, so large instances are safe from privacy concerns but can easily be DoS'd.
1. Has affected all instances since we used UeberDB w/ MySQL [4+ years].
1. Only affects instances running MySQL/PostgreSQL/SQLite [needs confirmation]

Steps to replicate.
1. Bring up Etherpad instance
1. Configure that instance to use MySQL
1. Create two pads, one with a ```*``` in the padID (Other special characters IE % and _ should be tested too)
1. Etherpad will download all pads?  Profit?

I am going to bring up an instance now to test on.

**Comment by nashe** [comment]
> Did your email bounce? Did you get a response?

No and no :-/ Tried your personal email and contact@etherpad.org. Also left a comment on your website with my contact details.

**Comment by JohnMcLear** [comment]
I'm unable to replicate this bug on latest windows release..  See my steps to replicate above.

**Comment by nashe** [comment]
This issue is worse than this and I can provide you a working proof-of-concept, but not here in public.

**Comment by JohnMcLear** [comment]
Email me it please :)  I'm at my desk right now..
