### ISSUE TITLE
duplicate key value violates unique constraint "store_pkey"

### ISSUE THREAD

**Issue by 2Belette** [ether/ueberDB#117]
This happened in my log when Etherpad-lite crashed.

Why note using CREATE TABLE IF NOT EXISTS instead of a CREATE TABLE to avoid any potential race condition between the SELECT and the CREATE TABLE [here?](https://github.com/Pita/ueberDB/blame/f3369fdce3569c3f5b6718f1fae1f95d2f358428/postgres_db.js#L58)

CREATE TABLE IF NOT EXISTS was introduced in postgresql 9.1

**Comment by muxator** [comment]
Hi @2Belette,

I wholly agree that `CREATE TABLE IF NOT EXISTS` would be better than the current approach (here the link to the [release notes](https://www.postgresql.org/docs/9.1/release-9-1.html#AEN110925) for future reference).

PostgreSQL 9.1 is from 2011 and currently supported on old distroc such as CentOS 6/7 ([source](https://www.postgresql.org/download/linux/redhat/)):

|Distribution | Version |
| --- | --- |
| RHEL/CentOS/SL/OL 7 | **9.2** (also supplies package rh-postgresql95 and rh-postgresql94 via SCL) |
| RHEL/CentOS/SL/OL 6 | 8.4 (also supplies package **postgresql92**) |



I have a question about the possible race condition, however.

https://github.com/Pita/ueberDB/blob/f3369fdce3569c3f5b6718f1fae1f95d2f358428/postgres_db.js#L58-L65

The race we are talking about happens when there is still no table in the DB and two _different_ users hit this code section at the same time?

Do you think you experienced exactly this race? I am trying to understand if using `CREATE TABLE IF NOT EXISTS` would 100% solve this problem or is just an improvement and there is a worse problem hiding somewhere else.

Thanks

**Comment by JohnMcLear** [comment]
@2Belette Can you still replicaet this on latest version?

**Comment by JohnMcLear** [comment]
Changed to create if not exists.
